inputs = [
    "Thirty-five crates of ceramic pottery, each weighing 120 kilograms. The pottery is wrapped in bubble wrap and secured within the crates to prevent damage during transit.",
    "Ten barrels of spirits, each filled with 200 liters of premium whiskey. Each barrel weighs 250 kilograms and is made from charred oak to enhance flavor.",
    "Twenty containers of industrial oil, each containing 500 kilograms. The oil is stored under strict environmental standards to ensure safety and quality.",
    "Forty sacks of apples, each weighing 10 kilograms. The apples are fresh and require cool, ventilated storage to maintain their crispness.",
    "Fifty packets of bolts, each packet contains 500 pieces. Each packet weighs 10 kilograms and is essential for construction projects.",
    "Twenty drums of flammable chemicals, packed securely in fireproof containers. Each drum weighs 150 kilograms and is marked as hazardous.",
    "Fifteen casks of alcoholic beverages, specifically craft beer, each holding 100 liters. Each cask weighs 90 kilograms and is kept at a controlled temperature.",
    "Eight pallets of paint, carefully packed to prevent spillage during transit. Each pallet contains 40 buckets of paint, and each bucket weighs 5 kilograms.",
    "Sixty bins of textiles, each filled with 200 meters of fabric. Each bin weighs 50 kilograms and the fabrics are sensitive to moisture.",
    "Thirty jugs of pharmaceuticals, each containing 10 liters of liquid medication. Each jug weighs 12 kilograms and requires refrigeration.",
    "Twenty-five cases of luxury goods, including designer handbags and watches. Each case weighs 15 kilograms and is monitored for security.",
    "Five totes of raw materials, specifically copper wire, each weighing 200 kilograms. The materials are crucial for electrical manufacturing.",
    "Twelve packs of stationery, each pack containing 1000 items like pens and notebooks. Each pack weighs 20 kilograms.",
    "Forty packets of food products, specifically organic nuts, each weighing 5 kilograms. The packets are vacuum-sealed to preserve freshness.",
    "Eighteen canisters of hazardous petroleum, each canister designed to hold 100 liters. Each weighs 80 kilograms and is handled with extreme caution.",
    "Fourteen tubs of cosmetics, including creams and lotions, each tub weighing 3 kilograms. The cosmetics are sensitive to temperature changes.",
    "Nine jars of perfume, each jar delicately crafted and containing 1 liter. Each jar weighs 2 kilograms and is wrapped in anti-shock packaging.",
    "Seven drums of construction materials, specifically asphalt, each drum weighing 300 kilograms. The materials are used for road paving.",
    "Fifty bags of agricultural products, specifically organic coffee beans, each bag weighing 10 kilograms. The beans are stored in cool, dry conditions.",
    "Thirty-two envelopes of jewelry, each envelope contains several pieces of fine jewelry. Each envelope weighs 0.5 kilograms and requires secure transport.",
    "Sixteen bottles of olive oil, each bottle holding 1 liter. Each bottle weighs 1 kilogram and is stored under organic certification standards.",
    "Twenty-two tanks of medical supplies, including oxygen and nitrous oxide, each tank weighing 50 kilograms. The tanks are essential for hospital use.",
    "Nineteen vials of hazardous chemicals, specifically bio-reactive agents. Each vial weighs 0.1 kilograms and is handled with bio-safety protocols.",
    "Thirteen bins of wood products, specifically crafted wooden toys. Each bin weighs 25 kilograms and is made from sustainably sourced wood.",
    "Twenty-four boxes of musical instruments, including guitars and violins. Each box weighs 8 kilograms and is padded for shock absorption."
]