inputs = [
    "Fifty drums of petroleum, each weighing 150 kilograms.",
    "Thirty cases of luxury goods, including jewelry and perfumes, with a total weight of 250 pounds.",
    "Eight pallets of coffee beans, each pallet weighs 900 kilograms.",
    "Twelve tanks of industrial glue, each containing 100 liters and weighing 200 kg each.",
    "Twenty cans of paint, each can weighs 5 kilograms.",
    "Forty sacks of agricultural products, primarily coffee beans, each sack weighs 50 kg.",
    "Fifteen crates of electronic components, each crate weighs 25 kilograms.",
    "Twenty bottles of spirits, each bottle contains 750 milliliters and weighs 1 kilogram.",
    "Ten tubs of cosmetics, each tub contains 2 kilograms of product.",
    "Sixty packets of pharmaceuticals, each packet weighs 500 grams.",
    "One hundred jars of olive oil, each jar contains 1 liter and weighs 1.2 kilograms.",
    "Eighteen casks of wine, each cask weighs 160 kilograms and is made from oak.",
    "Twenty-five totes of hazardous waste, securely packed, each tote weighs 50 pounds and is marked as hazardous.",
    "Fifty boxes of stationery, including pens and paper, each box weighs 5 kilograms.",
    "Thirty envelopes of artwork, each envelope contains 10 items and weighs 2 kilograms.",
    "Twenty-five drums of flammable chemicals, each drum contains 200 liters and weighs 210 kg, marked as hazardous.",
    "Fifteen pallets of machinery, each pallet includes various mechanical parts and weighs 3 tonnes.",
    "Twenty bins of toys, each bin includes 100 pieces and weighs 30 pounds.",
    "Ten tanks of oxygen, each weighing 300 kilograms and marked for medical use.",
    "Forty jugs of industrial oil, each jug contains 10 liters and weighs 12 kilograms.",
    "Seventeen canisters of raw materials, including metals and plastics, each canister weighs 40 kilograms.",
    "Twelve vials of pharmaceuticals, each vial contains 100 milliliters and weighs 100 grams.",
    "Thirty crates of automotive parts, each crate weighs 40 kilograms.",
    "Twenty barrels of hazardous chemicals, each weighing 180 kg, properly labeled and packed for safety.",
    "Fifty containers of textiles, including cotton and synthetic fabrics, each container weighs 20 pounds."
]