inputs = [
    "Twenty drums of industrial oil, each weighing 200 kilograms. This shipment is essential for heavy machinery lubrication.",
    "Thirty-five jars of cosmetics, delicately packed, each jar weighing 0.5 kilograms. Products include various skin care creams.",
    "Eighteen pallets of electronics, each pallet holding 50 boxes. Each box contains multiple electronic devices, total weight per pallet is 300 kilograms.",
    "Fifteen cases of ceramic pottery, each case weighing 25 kilograms. Fragile items packed with extra padding.",
    "Forty bins of toys, each bin contains assorted children's toys weighing a total of 50 kilograms per bin.",
    "One-hundred-and-ten sacks of coffee beans, each weighing 50 kilograms. Organic and fair-trade certified coffee beans.",
    "Twenty-two tanks of petroleum, each tank weighs 2,000 kilograms. These are classified as hazardous cargo.",
    "Sixty bottles of perfumes, each bottle weighs 1 kilogram. Fragrances for both men and women included.",
    "Twenty-five crates of stationery, each crate includes various office supplies weighing 20 kilograms total.",
    "Twelve casks of spirits, each cask containing 100 litres, total weight per cask is 120 kilograms.",
    "Forty jugs of agricultural products, including bio fertilizers and pesticides, each jug weighs 10 kilograms.",
    "Fifty barrels of alcoholic beverages, assorted beers and wines, each barrel weighs 150 kilograms.",
    "Seven containers of flammable chemicals, each container weighs 200 kilograms. This is classified as hazardous cargo.",
    "Thirty canisters of pharmaceuticals, including various medications and vaccines, each canister weighs 5 kilograms.",
    "Twenty-two packets of luxury goods, including designer clothing and accessories, each packet weighs 2 kilograms.",
    "Eighteen vials of raw materials for cosmetic production, each vial weighing 0.3 kilograms. Ingredients include essential oils.",
    "Ten drums of construction materials, primarily nails and screws, each drum weighs 300 kilograms.",
    "Twenty-four boxes of musical instruments, each box contains five instruments, total weight per box is 50 kilograms.",
    "Sixteen cans of paint, each can weighs 5 kilograms. Non-toxic and water-based paints.",
    "Twelve bags of steel parts for machinery, each bag weighs 100 kilograms. Includes bolts and nuts.",
    "Nine totes of clothing, assorted seasonal apparel for men and women, each tote weighs 40 kilograms.",
    "Fourteen envelopes of artwork, including paintings and sketches, each envelope weighs 1 kilogram.",
    "Thirty-three containers of hazardous waste, each container securely packed and weighs 500 kilograms.",
    "Fifty-one buckets of industrial glue, each bucket weighs 10 kilograms. Used in construction and manufacturing.",
    "Twenty-nine tanks of oxygen, medical grade, each tank weighs 100 kilograms. Essential for healthcare facilities."
]
