cargo_items = [
    "olive oil",
    "apples",
    "ceramic pottery",
    "spirits",
    "industrial oil",
    "bolts",
    "machinery",
    "petroleum",
    "paint",
    "equipment",
    "chemicals",
    "textiles",
    "automobile parts",
    "engine components",
    "electronics",
    "furniture",
    "plastics",
    "medical supplies",
    "steel",
    "wood products",
    "pharmaceuticals",
    "raw materials",
    "construction materials",
    "cosmetics",
    "alcoholic beverages",
    "glassware",
    "toys",
    "agricultural products",
    "luxury goods",
    "stationery",
    "sporting goods",
    "packaging materials",
    "household goods",
    "food products",
    "perfumes",
    "clothing",
    "jewelry",
    "musical instruments",
    "artwork",
    "office supplies"
]

packaging_plural = [
    "drums",
    "containers",
    "tubs",
    "cans",
    "vials",
    "packs",
    "sacks",
    "tanks",
    "cases",
    "packets",
    "crates",
    "casks",
    "totes",
    "barrels",
    "jugs",
    "flasks",
    "envelopes",
    "bins",
    "canisters",
    "barrels",
    "tins",
    "drums",
    "bags",
    "bottles",
    "packets",
    "crates",
    "jars",
    "boxes",
    "pallets",
]